### ISSUE TITLE
Could not Analyze  target/cljsbuild/public/js/out/monaco/api/refs.cljs

### ISSUE THREAD

**Issue by youkale** [just-sultanov/clj-monaco#13]
### project.clj
```
 :dependencies [[org.clojure/clojure "1.10.1"]
                 [ring-server "0.5.0"]
                 [reagent "0.10.0"]
                 [reagent-utils "0.3.3"]
                 [ring "1.8.1"]
                 [ring/ring-defaults "0.3.2"]
                 [hiccup "1.0.5"]
                 [yogthos/config "1.1.7"]
                 [org.clojure/clojurescript "1.10.773"
                  :scope "provided"]
                 [metosin/reitit "0.5.1"]
                 [metosin/jsonista "0.2.6"]
                 [pez/clerk "1.0.0"]
                 [venantius/accountant "0.2.5"
                  :exclusions [org.clojure/tools.reader]]

                 [cljs-ajax "0.8.0"]
                 [re-frame "1.0.0"]
                 [luminus-transit "0.1.2"]
                 [day8.re-frame/http-fx "0.2.1"]
                 [com.cognitect/transit-clj "1.0.324"]
                 [antizer "0.3.1" :exclusions [[cljsjs/antd]]]
                 [cljsjs/antd "3.8.0-0" :exclusions [[cljsjs/react] [cljsjs/react-dom]]]
                 [clj-monaco "0.0.9" :exclusions [[org.clojure/clojure] [org.clojure/clojurescript] [reagent]]]]

:figwheel
  {:http-server-root "public"
   :server-port      3449
   :nrepl-port       7002
   :nrepl-middleware [cider.piggieback/wrap-cljs-repl]
   :css-dirs         ["resources/public/css"]
   :ring-handler     cash.handler/app}
```

## lein figwheel

OpenJDK 64-Bit Server VM warning: forcing TieredStopAtLevel to full optimization because JVMCI is enabled
Figwheel: Cutting some fruit, just a sec ...
OpenJDK 64-Bit Server VM warning: forcing TieredStopAtLevel to full optimization because JVMCI is enabled
Figwheel: Validating the configuration found in project.clj
Figwheel: Configuration Valid ;)
Figwheel: Starting server at http://0.0.0.0:3449
Figwheel: Watching build - app
Compiling build :app to "target/cljsbuild/public/js/app.js" from ["src/cljs" "src/cljc" "env/dev/cljs"]...
Failed to compile build :app from ["src/cljs" "src/cljc" "env/dev/cljs"] in 8.528 seconds.
----  Could not Analyze  target/cljsbuild/public/js/out/monaco/api/refs.cljs  ----

  No such namespace: monaco, could not locate monaco.cljs, monaco.cljc, or JavaScript source providing "monaco" 

----  Analysis Error : Please see target/cljsbuild/public/js/out/monaco/api/refs.cljs  ----
Figwheel: initial compile failed - outputting temporary helper application to target/cljsbuild/public/js/app.js
Figwheel: Starting CSS Watcher for paths  ["resources/public/css"]

**Comment by just-sultanov** [comment]
This library is experimental and works with [shadow-cljs](https://shadow-cljs.github.io/). Figwheel is not supported.
